EQUIPMENT_INSTANCES:
  - equipment:
      code: BioLector1
      data:
        instance_id: biolector_devonshire10
        institute: NCL
      requirements:
        write_file: tmp.csv
  - equipment:
      code: BioLector1
      data:
        instance_id: biolector_manchester4
        institute: MAN
      requirements:
        write_file: tmp2.csv
  - equipment:
      code: BioLector1
      data:
        instance_id: biolector_london22
        institute: LDN
      requirements:
        write_file: tmp3.csv

OUTPUTS:
  - code: MQTT
    broker: localhost
    port: 1883
    username: mcrowther
    password: Radeon12300
    fallback: KEYDB

  - code: KEYDB
    host: localhost
    port: 6379
    db: 0
    fallback: FILE

  - code: FILE
    filename: local.json
    fallback: null
